POST http://localhost:5000/auth/register
Content-Type: application/json

{
  "username": "Jamie",
  "email": "jamieomondi@mail.com",
  "password": "password"
}

###
POST http://localhost:5000/auth/login
Content-Type: application/json

{
  "email": "jamieomondi@mail.com",
  "password": "password"
}

###
POST http://localhost:5000/auth/logout
Content-Type: application/json

{
  "email": "jamieomondi@mail.com",
  "password": "password"
}